name: webpack build #Define the name of the work flow

# define when the workflow should trigger
on:
  push:
    branches: [master, main]

# define the jobs that are to be executed
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5 #pulls this repository into the environment
    - uses: actions/setup-node@v4 #sets up the node envirnoment
      with:
          node-version: '24'
    - run: npm ci
    - run: npm run build --if-present # runs build command in project if its present

